### ISSUE TITLE
Image in singe line question is not parsed correctly 

### ISSUE THREAD

**Issue by scaturigo** [c-okelly/anki-remote-decks#8]
Image inside front part are not displayed correctly. Is it normal ?

**Comment by c-okelly** [comment]
Still looking into it. Will give an update when I have it nearly fixed!

**Comment by c-okelly** [comment]
Possibly looking like the weekend at the earliest tbh. I have uncovered more issues as I've been trying to fix this!

**Comment by c-okelly** [comment]
This issues has uncovered another bug.

The image src being used in `<img src="$">` was a url. This means if the card was accessed offline the image would not load.

In addition to this if an image file is missing for a question it is not automatically uploaded.

In order to fix these issues the following must be done:

- [ ] 
- [ ] 
- [ ]

**Comment by c-okelly** [comment]
The fix i went with as a stop gap ensure that during a sync every media item is readded to Anki. This is currently very heavy.

image names are based upon "downloaded_image${hash_of_url}"

This should ensure the name does not change unless the image url changes. I have manually tested this and it word on multiple syncs and image updating

**Comment by c-okelly** [comment]
Closed by #16

Could do with some refactoring though...
